version: '3.1'

services:

  mysql:
    container_name: mysqldb
    image: mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_system
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234"]
      timeout: 20s
      retries: 10



  springboot-app:
    container_name: spring-app
    image: springboot-app
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306    # we are in same network so we connect internally.
    depends_on:
      mysqldb:
        condition: service_healthy